### ISSUE TITLE
Showing signature pad on button click

### ISSUE THREAD

**Issue by azakordonets** [blackjk3/react-signature-pad#8]
Hi, i've very new to React and javascript and i was trying to use your library. Right now, when i add it to render method of my page, get this signature pad loaded right away. How can i call appearance of this canvas on button click and how can i add "Save" button to this component?

**Comment by SystemParadox** [comment]
If you want it to appear after a button click, you can add a state flag like this:

```
var SignaturePage = React.createClass({
    getInitialState: function () {
        return {
            showSignature: false,
        };
    },

    handleShow: function () {
        this.setState({ showSignature: true });
    },

    render: function () {
        return (
            <div>
                <button onClick={ this.handleShow }>Show</button>
                { this.state.showSignature && (
                    <SignaturePad ref='signature' />
                )}
                <button onClick={ this.handleSave }>Save</button>
            </div>
        );
    }
}
```

I would advise using the example CSS as a starting point, but modifying it as appropriate to fit your needs. For example, if you want it to be shown inline on the page, you will want to remove all of the styling that makes it look like a popup.

If you do want it in a popup, you will need to make your own popup so that you can add the save button to it. You could use the provided CSS as a starting point, but you will want to move it to your own wrapper container.

**Comment by azakordonets** [comment]
Got it, thanks
